name: PullRequest review labeler
on:
  pull_request_review:
  pull_request:
    types: [ review_requested ]

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    name: A job to say hello
    steps:
      - name: "LABEL!"
        uses: chaikaOrg/org-label-bot@main
        with:
          bot-app-id: ${{ vars.LABELER_APP_ID }}
          bot-app-key: ${{ secrets.LABELER_APP_PRIVATE_KEY }}
