name: PullRequest review labeler
on:
  pull_request_review:
  pull_request:
    types: [ review_requested ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: chaikaOrg/org-label-bot@main
        with:
          secret-input: 'Mona the Octocat'
